### ISSUE TITLE
Report emails: do not show ALL the report in the email body

### ISSUE THREAD

**Issue by quigger** [bobf/database_reports#1]
As a Database Reports user I want to have my report attached to the email and ONLY see a snippet of the report in the body of the email.

Some reports might be very long (or wide) and do not translate well to email.

e.g.
![image](https://user-images.githubusercontent.com/644502/170974492-a380bb6b-ef8f-4fe0-b01c-11297a01f19c.png)

As a user I would prefer 2-3 rows of sample data limited to 5-6 headings?
(explaining that only some data is shown for readability).

**Comment by bobf** [comment]
Fixed by 478d5ed11f951d8a4234562a19ffc04110ca1185
