### ISSUE TITLE
LOW: can we change the title of the pages (browser tab)

### ISSUE THREAD

**Issue by quigger** [bobf/database_reports#3]
As a Database Reports user it would be nice to see the tabs of the browser display better names to match the page you are on.

e.g.
https://database-reports.homeflow.co.uk/reports
Current: DatabaseReports
Suggested: List Reports - Database Reports

https://database-reports.homeflow.co.uk/reports/new
Current: DatabaseReports
Suggested: New Report - Database Reports

**Comment by quigger** [comment]
Not deployed?

**Comment by bobf** [comment]
@quigger Correct.
